// Generated by ../../brand/render.mjs. Do not edit — edit brand/lib/marks.mjs
// and re-run `npm run render` there.
//
// The four, as a pixel grid. The header needs the shape rather than a file:
// an <img> cannot be tinted, and the mark has to take the colour of whatever
// it sits on.
export const MARK_SIZE = 12;

export const MARK_GRID = [
  "............",
  ".......##...",
  "......###...",
  ".....####...",
  "....##.##...",
  "...##..##...",
  "..##...##...",
  "..########..",
  "..########..",
  ".......##...",
  ".......##...",
  "............",
] as const;
